### ISSUE TITLE
Feature novendor doesn't compile with newest libbpf

### ISSUE THREAD

**Issue by crapStone** [libbpf/libbpf-rs#275]
I have `libbpf` version `1.0.1` installed and when compiling `libbpf-rs` version `0.18.0` with the `novendor` feature the following error occurs:

```
warning: In file included from bindings.c:1:
warning: bindings.h:7:10: fatal error: bpf/xsk.h: No such file or directory
warning:     7 | #include <bpf/xsk.h>
warning:       |          ^~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `libbpf-sys v0.8.3+v0.8.1`
```

The problem is, that on crates.io `libbpf-rs` version `0.18.0` depends on `libbpf-sys` version `0.8.0` (see [here](https://crates.io/crates/libbpf-rs/0.18.0/dependencies)) and not `1.0.0` like in the `master` branch.

**Comment by danielocfb** [comment]
> @danielocfb we should probably release libbpf-rs version that depends on libbpf-sys 1.0 so that issues like this don't pop up. WDYT?

I think we should. Internal folks also seemed to have asked for that.

**Comment by danielocfb** [comment]
We just published `libbpf-rs` version `0.19`, which works with `libbpf` `1.0`. So this should address the issue you were seeing. Let us know if that's not the case.
